name: Update release

on:
  push:
    tags:
    - '*'
  workflow_dispatch:

jobs:
  merge-to-stable:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4.1.1
      with:
        token: ${{ secrets.NCRONTABPAT }}
        persist-credentials: false
        fetch-depth: 0

    - name: Set git config
      run: |
        git config --local user.email "linkdotnet@action.com"
        git config --local user.name "LinkDotNet Bot"
    
    - name: Merge main to stable
      run: |
        git fetch
        git checkout stable
        git pull
        git merge --no-ff -X theirs origin/main -m "Updating to newest release"
        
    - name: Push changes
      uses: ad-m/github-push-action@v0.8.0
      with:
        github_token: ${{ secrets.SBPAT }}
        branch: stable
        force: true